### ISSUE TITLE
Can't start examples

### ISSUE THREAD

**Issue by brandonmp** [nsmith7989/redux-filter#32]
Ubuntu 16.04, node 6.3.1, npm 3.10.3

terminal dump is below, but getting repeated instances of this error after `clone`, `npm install`, `npm start` in the example folders:

```
Module build failed: ReferenceError: [BABEL] /home/bmp/code/redux-filter/examples/product-filtering/node_modules/webpack-hot-middleware/client-overlay.js: Unknown option: /home/bmp/code/redux-filter/.babelrc.presets
```

Not familiar with a lot of the packages in this project (eg `browsersync`) so wasn't able to troubleshoot myself.

happy to provide more info or try solutions if you have ideas.

Thanks!

```
$ npm start
> product-filtering@1.0.0 start /home/bmp/code/redux-filter/examples/product-filtering
> node devServer.js

[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3002
    External: http://192.168.8.101:3002
 --------------------------------------
          UI: http://localhost:3003
 UI External: http://192.168.8.101:3003
 --------------------------------------
[BS] Serving files from: ./
[BS] Watching files...
webpack built 596c858508cc976530af in 387ms
Hash: 596c858508cc976530af
Version: webpack 1.13.1
Time: 387ms
    Asset     Size  Chunks       Chunk Names
bundle.js  35.7 kB       0       filter
chunk    {0} bundle.js (filter) 4.53 kB [rendered]
    [0] multi filter 40 bytes {0} [built] [1 error]
    [1] (webpack)-hot-middleware/client.js?reload=true 4.49 kB {0} [built] [5 errors]

ERROR in ./index.js
Module build failed: ReferenceError: [BABEL] /home/bmp/code/redux-filter/examples/product-filtering/index.js: Unknown option: /home/bmp/code/redux-filter/.babelrc.presets
    at Logger.error (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:71:12)
 @ multi filter

ERROR in (webpack)-hot-middleware/client-overlay.js
Module build failed: ReferenceError: [BABEL] /home/bmp/code/redux-filter/examples/product-filtering/node_modules/webpack-hot-middleware/client-overlay.js: Unknown option: /home/bmp/code/redux-filter/.babelrc.presets
    at Logger.error (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:71:12)
 @ (webpack)-hot-middleware/client.js?reload=true 99:14-41

ERROR in (webpack)-hot-middleware/process-update.js
Module build failed: ReferenceError: [BABEL] /home/bmp/code/redux-filter/examples/product-filtering/node_modules/webpack-hot-middleware/process-update.js: Unknown option: /home/bmp/code/redux-filter/.babelrc.presets
    at Logger.error (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:71:12)
 @ (webpack)-hot-middleware/client.js?reload=true 121:20-47

ERROR in ./~/querystring/index.js
Module build failed: ReferenceError: [BABEL] /home/bmp/code/redux-filter/examples/product-filtering/node_modules/querystring/index.js: Unknown option: /home/bmp/code/redux-filter/.babelrc.presets
    at Logger.error (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:71:12)
 @ (webpack)-hot-middleware/client.js?reload=true 13:20-42

ERROR in ./~/strip-ansi/index.js
Module build failed: ReferenceError: [BABEL] /home/bmp/code/redux-filter/examples/product-filtering/node_modules/strip-ansi/index.js: Unknown option: /home/bmp/code/redux-filter/.babelrc.presets
    at Logger.error (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:71:12)
 @ (webpack)-hot-middleware/client.js?reload=true 95:14-35

ERROR in (webpack)/buildin/module.js
Module build failed: ReferenceError: [BABEL] /home/bmp/code/redux-filter/examples/product-filtering/node_modules/webpack/buildin/module.js: Unknown option: /home/bmp/code/redux-filter/.babelrc.presets
    at Logger.error (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/bmp/code/redux-filter/examples/product-filtering/node_modules/babel-loader/index.js:71:12)
 @ (webpack)-hot-middleware/client.js?reload=true 1:0-41

```

**Comment by notrab** [comment]
Same issue here. See https://github.com/nsmith7989/redux-filter/issues/29#issue-162430210
